<?php
session_start();
include 'db_connect.php';
require_once('tcpdf/tcpdf.php'); // ✅ include TCPDF

if (!isset($_SESSION['admin_id'])) {
    die("Access denied. Admin not logged in.");
}

$admin_id = $_SESSION['admin_id'];

// Fetch complaint counts
$total      = $conn->query("SELECT COUNT(*) AS total FROM Complaints")->fetch_assoc()['total'];
$resolved   = $conn->query("SELECT COUNT(*) AS resolved FROM Complaints WHERE Status = 'Resolved'")->fetch_assoc()['resolved'];
$pending    = $conn->query("SELECT COUNT(*) AS pending FROM Complaints WHERE Status = 'Pending'")->fetch_assoc()['pending'];
$inprogress = $conn->query("SELECT COUNT(*) AS inprogress FROM Complaints WHERE Status = 'In Progress'")->fetch_assoc()['inprogress'];

// Report content (shared)
$report_text = "Complaint Report Summary\n";
$report_text .= "----------------------------\n";
$report_text .= "Total Complaints: $total\n";
$report_text .= "Resolved: $resolved\n";
$report_text .= "Pending: $pending\n";
$report_text .= "In Progress: $inprogress\n";
$report_text .= "Generated by Admin ID: $admin_id\n";
$report_text .= "Date: " . date('Y-m-d H:i:s') . "\n";

// Handle save
if (isset($_POST['generate'])) {
    $stmt = $conn->prepare("INSERT INTO Report (AdminID, GeneratedReport) VALUES (?, ?)");
    $stmt->bind_param("is", $admin_id, $report_text);

    if ($stmt->execute()) {
        $success = "Report saved successfully.";
    } else {
        $error = "Error saving report: " . $stmt->error;
    }
}

// Handle PDF download
if (isset($_POST['download_pdf'])) {
    $pdf = new TCPDF();
    $pdf->AddPage();
    $pdf->SetFont('helvetica', '', 12);
    $pdf->Write(0, $report_text);
    $pdf->Output('complaint_report.pdf', 'D'); // D = force download
    exit;
}
?>

<!DOCTYPE html>
<html>
<head>
    <title>Admin Report Center</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <style>
    body {
        font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
        margin: 0;
        padding: 40px;
        background: #f0f4f8;
        color: #2d3748;
        animation: fadeIn 0.6s ease-in-out;
    }
    
    .container {
        max-width: 800px;
        margin: 0 auto;
        background: white;
        padding: 40px;
        border-radius: 12px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }

    .container:hover {
        transform: translateY(-2px);
        box-shadow: 0 8px 20px rgba(0, 0, 0, 0.12);
    }

    h2 {
        color: #2b6cb0;
        font-size: 2.2rem;
        margin-bottom: 30px;
        padding-bottom: 15px;
        border-bottom: 3px solid #e2e8f0;
        display: flex;
        align-items: center;
        gap: 10px;
    }

    textarea {
        width: 100%;
        height: 300px;
        padding: 20px;
        border: 2px solid #e2e8f0;
        border-radius: 8px;
        font-family: 'Courier New', monospace;
        font-size: 0.95rem;
        line-height: 1.6;
        margin: 25px 0;
        background: #f8fafc;
        resize: vertical;
        transition: all 0.3s ease;
    }

    textarea:hover {
        background: #edf2f7;
        border-color: #90cdf4;
    }

    textarea:focus {
        outline: none;
        border-color: #63b3ed;
        background-color: #ffffff;
        box-shadow: 0 0 5px rgba(66, 153, 225, 0.4);
    }

    form {
        position: relative;
    }

    .button-group {
        display: flex;
        gap: 15px;
        margin-top: 20px;
    }

    button {
        padding: 12px 25px;
        border: none;
        border-radius: 6px;
        font-weight: 600;
        cursor: pointer;
        transition: all 0.2s ease;
        display: inline-flex;
        align-items: center;
        gap: 10px;
        font-size: 1rem;
    }

    button[name="generate"] {
        background: #4299e1;
        color: white;
    }

    button[name="download_pdf"] {
        background: #48bb78;
        color: white;
    }

    button:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.15);
    }

    button[name="generate"]:hover {
        background: #3182ce;
    }

    button[name="download_pdf"]:hover {
        background: #38a169;
    }

    a {
        display: inline-block;
        margin-top: 25px;
        color: #4299e1;
        text-decoration: none;
        font-weight: 500;
        transition: color 0.2s ease, transform 0.2s ease;
    }

    a:hover {
        color: #2b6cb0;
        text-decoration: underline;
        transform: translateX(-3px);
    }

    .success, .error {
        padding: 15px;
        border-radius: 6px;
        margin: 20px 0;
        font-weight: 500;
        display: flex;
        align-items: center;
        gap: 10px;
    }

    .success {
        background: #f0fff4;
        color: #2f855a;
        border: 1px solid #c6f6d5;
    }

    .error {
        background: #fff5f5;
        color: #c53030;
        border: 1px solid #fed7d7;
    }

    @keyframes fadeIn {
        from {
            opacity: 0;
            transform: translateY(20px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }

    @media (max-width: 768px) {
        body {
            padding: 20px;
        }

        .container {
            padding: 25px;
        }

        h2 {
            font-size: 1.8rem;
        }

        .button-group {
            flex-direction: column;
        }

        button {
            justify-content: center;
        }
    }
</style>
</head>
<body>
<div class="container">
    <h2><i class="fas fa-chart-bar"></i> Complaint Report Center</h2>

    <?php if (isset($success)) echo "<div class='success'><i class='fas fa-check-circle'></i> $success</div>"; ?>
    <?php if (isset($error)) echo "<div class='error'><i class='fas fa-exclamation-triangle'></i> $error</div>"; ?>

    <form method="POST">
        <textarea readonly><?= $report_text ?></textarea>
        <div class="button-group">
            <button type="submit" name="generate"><i class="fas fa-database"></i> Save Report to Database</button>
            <button type="submit" name="download_pdf"><i class="fas fa-file-pdf"></i> Download as PDF</button>
        </div>
    </form>

    <a href="admin_dashboard.php"><i class="fas fa-arrow-left"></i> Back to Dashboard</a>
</div>
</body>
</html>


